### ISSUE TITLE
Filter not work

### ISSUE THREAD

**Issue by aluzardo** [stwe/dtbundle-demo#1]
I install the demo but I have problems with filters.

I use Postgresql.

![screen shot 2015-05-21 at 12 59 51](https://cloud.githubusercontent.com/assets/11529571/7748142/cffaf162-ffb9-11e4-9543-d6556f28e0c8.png)

What am I doing wrong?

**Comment by aluzardo** [comment]
I use MySQL and It works perfect. I need use Postgresql, ¿Is it posible?

**Comment by aluzardo** [comment]
I found the problem:

Postgresql doesn´t permit use like when the type of the column is integer.

It is the error:
                                                        ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
********** Error **********

ERROR: operator does not exist: integer ~~ unknown
SQL state: 42883
Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
Character: 49


How can I resolve?

**Comment by stwe** [comment]
see: https://github.com/stwe/DatatablesBundle/issues/124

**Comment by celvin** [comment]
https://github.com/stwe/DatatablesBundle/issues/124#issuecomment-121132259
